[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.9.0"
rocket = "0.5.0-rc.1"
tokio = { version = "1.13.1", features = ["full"]}
tonic = "0.6.1"
triggered = "0.1.2"

[build-dependencies]
tonic-build = "0.6.0"
