apiVersion: v1
kind: Service
metadata:
  name: greeting
spec:
  type: NodePort
  selector:
    app: greeting
  ports:
    - protocol: TCP
      port: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting
spec:
  selector:
    matchLabels:
      app: greeting
  replicas: 1
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
      - name: greeting
        image: "{{.Values.greeting.registry}}/{{.Values.greeting.repository}}:{{.Values.greeting.tag}}"
