apiVersion: v1
kind: Service
metadata:
  name: world
spec:
  selector:
    app: world
  ports:
    - protocol: TCP
      port: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: world
spec:
  selector:
    matchLabels:
      app: world
  replicas: 1
  template:
    metadata:
      labels:
        app: world
    spec:
      containers:
      - name: world
        image: "{{.Values.world.registry}}/{{.Values.world.repository}}:{{.Values.world.tag}}"


